import type { Metadata } from "next";
import { Inter, Nanum_Gothic, Raleway } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const nanum = Nanum_Gothic({
  subsets: ["latin"],
  style: "normal",
  weight: "400",
});
const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quizzington",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>{children}</body>
    </html>
  );
}
