import type { Metadata } from "next";
import { Noto_Sans, Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "./components/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils/authOptions";

// const nanum = Nanum_Gothic({
//   subsets: ["latin"],
//   style: "normal",
//   weight: "400",
// });
// const raleway = Raleway({ subsets: ["latin"] });
const noto_sans = Noto_Sans({ subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quizzington",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
